### ISSUE TITLE
Windows download blocked by Chrome

### ISSUE THREAD

**Issue by kurtextrem** [mangledbottles/screenlink#2]
![image](https://github.com/mangledbottles/screenlink-desktop/assets/502146/690ff247-efd4-446a-aadc-e9af7b39cf5e)
it says something like "Malicious file blocked". Just fyi.

**Comment by mangledbottles** [comment]
Hey @kurtextrem thanks for that! Did it give any reason why it is being blocked?
Chrome doesn't block it for me :)

**Comment by kurtextrem** [comment]
Didn't give any reason, hmm. Weird that it's blocked for me and isn't for you

**Comment by mangledbottles** [comment]
Hey @kurtextrem can you try do a fresh install and see if Chrome still blocks the download?
